# SPDX-FileCopyrightText: NVIDIA CORPORATION & AFFILIATES
# Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
"""
Locate and validate the reBot workflow params file.

Pure Python: no ``launch``, ``rclpy`` or ``ament_index_python`` imports, so every
branch below is unit testable with plain ``python3 -m pytest`` on a host with no
ROS install. ``launch/rebot_workflow.launch.py`` is the I/O shell.

Why the lookup is explicit instead of relying on the default
------------------------------------------------------------
``isaac_ros_manipulation_ros_python_utils.config.load_yaml_params`` falls back to
``isaac_ros_manipulation_bringup/params/<filename>`` when handed a bare filename
that does not resolve. In the released Isaac ROS container that directory is
read-only and contains the UPSTREAM ``sim_launch_params.yaml`` (UR robot, Robotiq
gripper). If the reBot params file is not found, that fallback would quietly bring
up a UR workflow instead of erroring, and the first symptom would be MoveIt
failing to find ``shoulder_pan_joint`` — a long way from the actual cause.

:func:`resolve_workflow_config_path` therefore resolves an explicit package
directory and raises :class:`WorkflowConfigError` when the canonical file is
absent. Environment-directory lookup remains available for compatibility tests
and external callers, but the supported launch file passes its own package
share directory.

The package-owned file is the only authored live workflow profile. The
workspace-level ``config/workflows`` path is a compatibility symlink to it.
"""

import os
from typing import Dict, Mapping, Optional, Tuple

#: Environment variable naming the directory that holds workflow params files.
WORKFLOW_CONFIG_DIR_ENV: str = 'ISAAC_ROS_MANIPULATION_WORKFLOW_CONFIG_DIR'

#: The reBot sim workflow params file, as installed into this package's
#: ``share/params`` and as expected inside the workflow config dir.
WORKFLOW_PARAMS_FILENAME: str = 'rebot_sim_launch_params.yaml'

#: Package whose ``share/params`` holds the authored copy of the params file.
DRIVER_UTILS_PKG: str = 'isaac_ros_manipulation_rebot_driver_utils'

#: The three keys ``workflows.launch.py`` and its children cannot run without.
#: ``use_sim_time`` is separate: it is checked by :func:`validate_workflow_params`
#: as a sim-profile assertion rather than as a mandatory-key check.
MANDATORY_KEYS: Tuple[str, ...] = ('workflow_type', 'camera_type', 'robot_type')

#: The six robot-description paths ``rebot_driver.launch.py`` declares without a
#: default, so they must be supplied by the params file or bringup fails on an
#: unsatisfied launch argument.
DESCRIPTION_PATH_KEYS: Tuple[str, ...] = (
    'urdf_path',
    'srdf_path',
    'joint_limits_file_path',
    'kinematics_file_path',
    'moveit_controllers_file_path',
    'ros2_controllers_file_path',
)

#: cuMotion inputs. The URDF is generated by ``rebot_b601dm_description``; the
#: XRDF is authored by another stage and may not exist yet, so its presence on
#: disk is deliberately NOT checked here (see :func:`validate_workflow_params`).
CUMOTION_KEYS: Tuple[str, ...] = (
    'cumotion_urdf_file_path',
    'cumotion_xrdf_file_path',
    'cumotion_joint_states_topic',
)

#: Key naming the driver launch file that ``drivers.launch.py`` includes.
ROBOT_LAUNCH_FILE_KEY: str = 'robot_launch_file_path'

#: Expected values for this robot and profile.
EXPECTED_ROBOT_TYPE: str = 'REBOT'
EXPECTED_CAMERA_TYPE: str = 'ISAAC_SIM'
EXPECTED_GRIPPER_TYPE: str = 'rebot_parallel'


class WorkflowConfigError(RuntimeError):
    """Raised when the workflow params file cannot be located or is invalid."""


def _missing_env_message() -> str:
    return (
        f'{WORKFLOW_CONFIG_DIR_ENV} is not set, so the reBot workflow params '
        f'file cannot be located.\n'
        f'\n'
        f'Refusing to fall back to the default params directory '
        f'(isaac_ros_manipulation_bringup/params). That directory is read-only '
        f'in the released container image and holds the UPSTREAM UR + Robotiq '
        f'sim_launch_params.yaml, so falling back would silently bring up a '
        f'different robot.\n'
        f'\n'
        f'Fix: run inside the workspace container, whose docker/entrypoint.sh '
        f'exports\n'
        f'    export {WORKFLOW_CONFIG_DIR_ENV}="${{ISAAC_ROS_WS}}/config/workflows"\n'
        f'or export it yourself, then populate it:\n'
        f'    mkdir -p "${WORKFLOW_CONFIG_DIR_ENV}"\n'
        f'    cp "$(ros2 pkg prefix --share {DRIVER_UTILS_PKG})"'
        f'/params/{WORKFLOW_PARAMS_FILENAME} \\\n'
        f'       "${WORKFLOW_CONFIG_DIR_ENV}"/\n'
    )


def _missing_file_message(config_dir: str, config_path: str) -> str:
    return (
        f'{WORKFLOW_CONFIG_DIR_ENV} is set to {config_dir!r} but '
        f'{config_path!r} does not exist.\n'
        f'\n'
        f'docker/entrypoint.sh exports this variable but does not create the '
        f'directory or copy the params file into it. Refusing to fall back to '
        f'isaac_ros_manipulation_bringup/params, which holds the upstream '
        f'UR + Robotiq params and would bring up a different robot.\n'
        f'\n'
        f'Fix:\n'
        f'    mkdir -p {config_dir}\n'
        f'    cp "$(ros2 pkg prefix --share {DRIVER_UTILS_PKG})"'
        f'/params/{WORKFLOW_PARAMS_FILENAME} \\\n'
        f'       {config_dir}/\n'
    )


def resolve_workflow_config_path(
    config_dir: Optional[str] = None,
    environ: Optional[Mapping[str, str]] = None,
    exists=os.path.exists,
    filename: str = WORKFLOW_PARAMS_FILENAME,
) -> str:
    """
    Return the absolute path of the reBot workflow params file.

    Args
    ----
        config_dir: Explicit params directory, normally the package share
            ``params`` directory. When omitted, use the legacy environment
            lookup.
        environ: Environment mapping to read
            :data:`WORKFLOW_CONFIG_DIR_ENV` from. Defaults to ``os.environ``.
            Used only when ``config_dir`` is omitted.
        exists: Predicate used to test for the file. Injected for the same
            reason; defaults to :func:`os.path.exists`.
        filename: Params file to look for inside the config directory.

    Returns
    -------
        str: Absolute path to the params file.

    Raises
    ------
        WorkflowConfigError: If the environment variable is unset or empty, or
            if the file is not present in the directory it names. Both messages
            carry the shell commands that fix the situation. Raising is
            deliberate: the alternative is a silent fall back to the upstream
            UR params file.

    """
    from_environment = config_dir is None
    if from_environment:
        env = os.environ if environ is None else environ
        config_dir = env.get(WORKFLOW_CONFIG_DIR_ENV, '')
        if not config_dir:
            raise WorkflowConfigError(_missing_env_message())

    config_path = os.path.join(config_dir, filename)
    if not exists(config_path):
        if not from_environment:
            raise WorkflowConfigError(
                f'The packaged reBot workflow params file {config_path!r} '
                f'does not exist. Rebuild {DRIVER_UTILS_PKG}; refusing to '
                f'fall back to the upstream UR + Robotiq profile.')
        raise WorkflowConfigError(
            _missing_file_message(config_dir, config_path))
    return config_path


def validate_workflow_params(params: Dict) -> None:
    """
    Assert that a loaded params dict can actually bring up the reBot sim workflow.

    Checks, in order: the three mandatory keys are present and non-empty;
    ``robot_type`` / ``camera_type`` / ``gripper_type`` hold the values this
    package implements; ``use_sim_time`` is the string ``'true'`` (this is the
    sim profile and there is no real profile in this build); the driver launch
    file key is present; the six description paths are present and non-empty; and
    the three cuMotion keys are present.

    Presence on disk is NOT checked for any path. ``$(ros2 pkg prefix ...)``
    substitutions have already been expanded by ``load_yaml_params`` by the time
    this runs, but the XRDF is authored by a separate stage and may legitimately
    not exist yet; failing on a missing XRDF here would block sim bringup for a
    file only cuMotion needs.

    Raises
    ------
        WorkflowConfigError: On the first problem found, naming the key.

    """
    for key in MANDATORY_KEYS:
        if not str(params.get(key, '')).strip():
            raise WorkflowConfigError(
                f'Workflow params are missing mandatory key {key!r}. '
                f'workflows.launch.py and its children read this key '
                f'unconditionally; a missing value surfaces much later as an '
                f'unsatisfied launch argument.')

    expected = {
        'robot_type': EXPECTED_ROBOT_TYPE,
        'camera_type': EXPECTED_CAMERA_TYPE,
        'gripper_type': EXPECTED_GRIPPER_TYPE,
    }
    for key, want in expected.items():
        got = str(params.get(key, ''))
        if got != want:
            raise WorkflowConfigError(
                f'Workflow params have {key}={got!r}, expected {want!r}. This '
                f'params file drives the reBot B601-DM in Isaac Sim; another '
                f'value routes bringup to a different robot, camera or gripper '
                f'and the mismatch surfaces as a missing joint or frame.')

    # Sim-only build: the real profile is not implemented, and ReBotDriverUtils
    # raises NotImplementedError when use_sim_time is false. Catching it here
    # gives the reason instead of a bare abstract-method failure.
    use_sim_time = str(params.get('use_sim_time', ''))
    if use_sim_time != 'true':
        raise WorkflowConfigError(
            f'Workflow params have use_sim_time={use_sim_time!r}, expected '
            f"'true'. This is a sim-only build: no real-hardware profile "
            f'exists for the reBot B601-DM in this package, and '
            f'ReBotDriverUtils raises NotImplementedError for a non-sim '
            f'launch. use_sim_time is per-profile, never global.')

    if not str(params.get(ROBOT_LAUNCH_FILE_KEY, '')).strip():
        raise WorkflowConfigError(
            f'Workflow params are missing {ROBOT_LAUNCH_FILE_KEY!r}. '
            f'drivers.launch.py raises ValueError without it, since that key '
            f'is the only thing telling it which robot to bring up.')

    for key in DESCRIPTION_PATH_KEYS:
        if not str(params.get(key, '')).strip():
            raise WorkflowConfigError(
                f'Workflow params are missing description path {key!r}. '
                f'rebot_driver.launch.py declares this launch argument with no '
                f'default, so bringup fails on an unsatisfied argument.')

    for key in CUMOTION_KEYS:
        if key not in params:
            raise WorkflowConfigError(
                f'Workflow params are missing cuMotion key {key!r}. cuMotion '
                f'is the default planning pipeline for this robot, so planning '
                f'fails without it.')
